defaults:
  - scope:
      path: "ipsa/*.md"
    values:
      layout: "ipsa"

defaults:
  - scope:
      path: "ipsa/plan.html"
    values:
      layout: "ipsa"

defaults:
  - scope:
      path: "ipsa/exercises.html"
    values:
      layout: "ipsa"

include:
  - "_*.txt"

menu:
  - title: "Welcome"
    url: "welcome"
  - title: "Course plan"
    url: "plan"
  - title: "Compact plan"
    url: "plan_compact"
  - title: "All slides (pdf)"
    url: "slides/all_slides.pdf"
  - title: "Exercises"
    url: "exercises"
  - title: "Handins"
    url: "handins"
  - title: "Final project"
    url: "project-intro"
  - title: "&nbsp;&nbsp;&nbsp;I - Medians"
    url: "project-1-medians"
  - title: "&nbsp;&nbsp;&nbsp;II - Portfolio"
    url: "project-2-portfolio"
  - title: "&nbsp;&nbsp;&nbsp;III - NMR"
    url: "project-3-nmr"
  - title: "&nbsp;&nbsp;&nbsp;IV - MNIST"
    url: "project-4-mnist"
  - title: "&nbsp;&nbsp;&nbsp;V - Open topic"
    url: "project-5-open-topic"
  - title: "Exam"
    url: "exam-rules"
  - title: "&nbsp;&nbsp;&nbsp;Statistics"
    url: "exam-statistics"
  - title: "&nbsp;&nbsp;&nbsp;Past exams"
    url: "exam-past"
  - title: "Plagiarism"
    url: "plagiarism"
  - title: "Workload"
    url: "workload"
  - title: "Literature"
    url: "literature"
  - title: "Python installation"
    url: "install-intro"
  - title: "&nbsp;&nbsp;&nbsp;Windows 10"
    url: "install-windows"
  - title: "&nbsp;&nbsp;&nbsp;Mac &amp; Linux"
    url: "install-mac-linux"
  - title: "Python resources"
    url: "resources-modules"
  - title: "&nbsp;&nbsp;&nbsp;Books"
    url: "resources-books"
  - title: "&nbsp;&nbsp;&nbsp;Videos"
    url: "resources-videos"
  - title: "AU course description"
    url: "https://kursuskatalog.au.dk/en/course/117934/Introduction-to-Programming-with-Scientific-Applications"
