defaults:
  -
    scope:
      path: "ipsa"
    values:
      layout: "ipsa"
  
include:
  - "_*.txt"  # otherwise __README__.txt is missing

menu:
  - title: "Welcome"
    url: "welcome"
  - title: "Course plan"
    url: "plan-full"
  - title: "&nbsp;-&nbsp;Compact"
    url: "plan-compact"
  - title: "&nbsp;-&nbsp;All slides (pdf)"
    url: "slides/all-slides.pdf"
  - title: "&nbsp;-&nbsp;All slides with answers (pdf)"
    url: "slides/all-slides-with-answers.pdf"
  - title: "Exercises"
    url: "exercises"
  - title: "Handins"
    url: "handins"
  - title: "Final project"
    url: "project-intro"
  - title: "&nbsp;-&nbsp;I - Medians"
    url: "project-1-medians"
  - title: "&nbsp;-&nbsp;II - Portfolio"
    url: "project-2-portfolio"
  - title: "&nbsp;-&nbsp;III - NMR"
    url: "project-3-nmr"
  - title: "&nbsp;-&nbsp;IV - MNIST"
    url: "project-4-mnist"
  - title: "&nbsp;-&nbsp;V - Open topic"
    url: "project-5-open-topic"
  - title: "Exam"
    url: "exam-rules"
  - title: "&nbsp;-&nbsp;Statistics"
    url: "exam-statistics"
  - title: "&nbsp;-&nbsp;Past exams"
    url: "exam-past"
  - title: "Plagiarism &amp; GAI"
    url: "plagiarism"
  - title: "Workload"
    url: "workload"
  - title: "Literature"
    url: "literature"
  - title: "Python installation"
    url: "install-intro"
  - title: "&nbsp;-&nbsp;Windows 11"
    url: "install-windows"
  - title: "&nbsp;-&nbsp;Mac &amp; Linux"
    url: "install-mac-linux"
  - title: "Python resources"
    url: "resources-modules"
  - title: "&nbsp;-&nbsp;Books"
    url: "resources-books"
  - title: "&nbsp;-&nbsp;Videos"
    url: "resources-videos"
  - title: "AU course description"
    url: "https://kursuskatalog.au.dk/en/course/130939/Introduction-to-Programming-with-Scientific-Applications"
